First commit nav
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P2-AllBooked pull request #29
Opened 2023-10-30 16:36 UTC by Mewlyscin

2023-10-30 17:52 UTC, YOUNS28100 approved these changes

2023-10-31 11:01 UTC, YOUNS28100 requested changes
Il manque un S à Paramètres dans le fichier menu burger

2023-10-31 17:48 UTC, ioayoub approved these changes

2023-11-05 07:17 UTC, Halicksse approved these changes

2023-11-05 15:07 UTC, YOUNS28100 approved these changes

2023-11-05 16:56 UTC, merged